#!/bin/bash

echo "Installing Compilers..."
sudo apt-get install -y gcc g++ make

echo "Installing Tools..."
xargs sudo apt-get install -y <tools 
stow git tmux

if ! which cargo > /dev/null; then
    echo "Installing Rust..."
    curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh
    source "$HOME/.cargo/env"
fi

echo "Installing Github CLI..."
type -p curl >/dev/null || sudo apt install curl -y
curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg &&\
    sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg &&
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null &&\
    sudo apt update &&\
    sudo apt install gh -y
gh auth login

echo "Installing Crates..."
xargs cargo install <crates
stow tealdeer

echo "Installing Node Version Manager..."
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
source ~/.bashrc
nvm install node
sudo npm install -g tree-sitter-cli neovim

echo "Stowing Bash..."
mv $HOME/.bashrc $HOME/.bashrc.bak
stow bash
source "$HOME/.bashrc"

echo "Installing Luarocks..."
sudo apt-get -y install luarocks

if [ $(dpkg-query -W -f='${Status}' neovim 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
    echo "Installing Neovim..."
    curl -sLO https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.deb &&\
        sudo dpkg -i nvim-linux64.deb &&\
        sudo rm nvim-linux64.deb &&\
        sudo apt install -f
fi
stow nvim

sudo apt-get install -y python3-dev python3-pip &&\
    sudo pip3 install --upgrade pynvim

echo "Installing Packages..."
xargs sudo apt-get install -y <packages

if [ ! -f '~/.bashrc' ]; then
    mv ~/.bashrc ~/.bashrc.bak
fi
stow bash
source ~/.bashrc
