#!/bin/bash

echo "Installing Compilers..."
sudo apt-get install -y gcc cc g++ make

echo "Installing Tools..."
xargs sudo apt-get install -y <tools 
stow git tmux

echo "Installing Rust..."; 
curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh

echo "Installing Crates..."
xargs cargo install <crates

stow bash tealdeer

echo "Installing Node..."
curl -fsSL https://deb.nodesource.com/setup_19.x | sudo -E bash - &&\
    sudo apt-get install -y nodejs &&\
    sudo npm install -g tree-sitter-cli neovim

echo "Installing Luarocks..."
sudo apt-get -y install luarocks

echo "Installing Neovim..."
curl -sLO https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.deb &&\
    sudo dpkg -i nvim-linux64.deb &&\
    sudo rm nvim-linux64.deb &&\
    sudo apt install -f
stow nvim

sudo apt-get install -y python-dev python-pip python3-dev python3-pip &&\
    sudo pip3 install --upgrade pynvim

echo "Installing Packages..."
xargs sudo apt-get install -y <packages

