---
- name: Install Node
  ansible.builtin.include_tasks: "{{ node_install_method }}.yml"

- name: Install global npm packages
  ansible.builtin.include_tasks: "npm_globals_{{ node_install_method }}.yml"
